import { GRID_SIZE, type Coord } from "./constants.ts";
import type { MissionIntelMark, MissionStageDefinition } from "./Campaign.ts";

const c = (x: number, y: number): Coord => ({ x, y });

/**
 * LEVIATHAN enters a search box already reduced by earlier watch sections.
 * The four named cells are deliberately left unmarked so its silent move has
 * four legal, publicly disclosed exits.  This is authored intelligence, not a
 * peek at runtime state.
 */
const leviathanOrigin = c(3, 3);
const leviathanEgress = [c(1, 1), c(6, 1), c(1, 6), c(6, 6)] as const;
const leviathanOpen = new Set([leviathanOrigin, ...leviathanEgress].map(({ x, y }) => `${x},${y}`));
const leviathanNet: MissionIntelMark[] = [];
for (let y = 0; y < GRID_SIZE; y += 1) for (let x = 0; x < GRID_SIZE; x += 1) {
  if (leviathanOpen.has(`${x},${y}`)) continue;
  leviathanNet.push({
    coord: c(x, y),
    mark: Math.abs(x - leviathanOrigin.x) + Math.abs(y - leviathanOrigin.y) === 1 ? "echo" : "miss",
  });
}

export const EXTREME_MISSIONS: ReadonlyArray<MissionStageDefinition> = [
  {
    id: 17,
    sortOrder: 10,
    difficulty: 6,
    category: "extreme",
    title: "FALSE WAKE",
    subtitle: "二つの聴音報告を照合し、損傷艦と潜航艦を一斉射で処理せよ。",
    directive: "指定海面ALPHA・BRAVOを順に聴音。報告確定後、MK-45 IIの二目標射撃で残存二艦を同時に無力化せよ。",
    condition: "指定SONAR 2回 / DD・SS撃沈 / MK-45 II 1回 / 3行動",
    fleet: ["battleship", "destroyer", "submarine"],
    playerFleet: ["battleship", "destroyer", "submarine"],
    enemyFleet: ["destroyer", "submarine"],
    enemyFirst: false,
    allowedWeapons: ["radar", "mk45"],
    objective: {
      kind: "scan-and-destroy",
      targets: ["destroyer", "submarine"],
      maxFriendlyActions: 3,
      reports: [
        { origin: c(2, 2), contact: true, code: "ALPHA / C-3:D-4" },
        { origin: c(4, 4), contact: false, code: "BRAVO / E-5:F-6" },
      ],
      orderedReports: true,
      requiredWeaponSequence: ["radar", "radar", "mk45"],
    },
    playerPlacements: [
      { id: "battleship", start: c(0, 7), orientation: "east" },
      { id: "destroyer", start: c(0, 5), orientation: "east" },
      { id: "submarine", start: c(7, 0), orientation: "east" },
    ],
    enemyPlacements: [
      { id: "destroyer", start: c(1, 3), orientation: "east" },
      { id: "submarine", start: c(6, 6), orientation: "east" },
    ],
    enemyInitialHits: [c(1, 3), c(2, 3)],
    enemyDisclosure: {
      known: ["destroyer"],
      unknownCount: 1,
      callsigns: { destroyer: "DD-03 GREYHOUND" },
      candidateCells: [
        { code: "LAST DD SECTION", coord: c(3, 3) },
        { code: "WAKE TERMINUS", coord: c(6, 6) },
      ],
      summary: "GREYHOUNDは2/3区画損傷。未識別音源一つ。聴音結果を確定し、射撃解を一つに絞れ。",
    },
    initialArsenal: { radar: 2, mk45: 1 },
    fixedSeed: 0x6e1701,
    aiSkill: 1.92,
    huntBreadth: 2,
    completion: {
      success: "CONTACT CORRELATION COMPLETE：二つの聴音報告を射撃解へ統合し、残存接触を一斉に減殺。",
      deadline: "CONTACT CORRELATION FAILED：聴音窓を消費。残存接触の同時処理に失敗。",
    },
  },
  {
    id: 18,
    sortOrder: 20,
    difficulty: 6,
    category: "extreme",
    title: "SEVERED LINK",
    subtitle: "一隻の護衛艦が支える二重連接を維持し、敵防空網から主力艦を順次切り離せ。",
    directive: "DE、CV、BBの順に撃沈。護衛艦による航空護衛連接・射撃管制連接を失わず、増加した全出撃・全射を使い切れ。",
    condition: "DE→CV→BB / 自軍CV・BB・DE生存 / F-4 2回・HARPOON 3回 / 5行動",
    fleet: ["carrier", "battleship", "escort", "submarine"],
    playerFleet: ["carrier", "battleship", "escort"],
    enemyFleet: ["carrier", "battleship", "escort", "submarine"],
    enemyFirst: false,
    allowedWeapons: ["phantom", "harpoon"],
    objective: {
      kind: "destroy-targets",
      targets: ["escort", "carrier", "battleship"],
      requiredDestructionOrder: ["escort", "carrier", "battleship"],
      protectedShips: ["carrier", "battleship", "escort"],
      maxFriendlyActions: 5,
      requiredWeaponUses: { phantom: 2, harpoon: 3 },
    },
    playerPlacements: [
      { id: "carrier", start: c(0, 0), orientation: "east" },
      { id: "escort", start: c(2, 2), orientation: "east" },
      { id: "battleship", start: c(0, 3), orientation: "east" },
    ],
    enemyPlacements: [
      { id: "escort", start: c(0, 0), orientation: "east" },
      { id: "carrier", start: c(2, 2), orientation: "east" },
      { id: "battleship", start: c(1, 6), orientation: "east" },
      { id: "submarine", start: c(7, 7), orientation: "east" },
    ],
    enemyInitialHits: [
      c(0, 0),
      c(2, 2), c(3, 2), c(4, 2), c(5, 2),
      c(2, 6), c(4, 6),
    ],
    initiallyIdentified: ["escort", "carrier", "battleship"],
    enemyDisclosure: {
      known: ["escort", "carrier", "battleship"],
      unknownCount: 1,
      callsigns: { escort: "DE-01 GATE", carrier: "CV-08 CITADEL", battleship: "BB-05 IRONCLAD" },
      summary: "GATE、CITADEL、IRONCLADを識別済み。SSは非目標。撃沈順序と二重連接の維持を優先せよ。",
    },
    requiredLinks: ["carrier", "battleship"],
    fixedSeed: 0x6e1801,
    aiSkill: 1.98,
    huntBreadth: 2,
    completion: {
      success: "SCREEN COLLAPSE CONFIRMED：護衛、航空母艦、戦艦の順に交戦能力を減殺。二重連接を全期間維持。",
      deadline: "LINK WINDOW LOST：指定順序または二重連接を維持できず、火力計画を中止。",
      protected: {
        carrier: "AIR GROUP LOST：航空母艦の戦闘能力喪失。航空打撃計画を中止。",
        battleship: "FIRE CONTROL LOST：戦艦の戦闘能力喪失。対水上打撃計画を中止。",
        escort: "ESCORT LINK SEVERED：護衛艦喪失。増加出撃・増加射の実施不能。",
      },
    },
  },
  {
    id: 19,
    sortOrder: 30,
    difficulty: 6,
    category: "extreme",
    title: "CROSS BEARING",
    subtitle: "二つの損傷船影を異なる射法で同時追跡し、二行動で交戦を終結せよ。",
    directive: "縦進するCAへ夾叉射撃、横進するDDへHARPOON。既存損傷と方位を照合し、CA、DDの順に撃沈せよ。",
    condition: "CA→DD / STRADDLE 1回・HARPOON 1回 / 2行動",
    fleet: ["battleship", "cruiser", "submarine"],
    playerFleet: ["battleship", "cruiser"],
    enemyFleet: ["cruiser", "destroyer", "submarine"],
    enemyFirst: false,
    allowedWeapons: ["sparrow", "harpoon"],
    objective: {
      kind: "destroy-targets",
      targets: ["cruiser", "destroyer"],
      requiredDestructionOrder: ["cruiser", "destroyer"],
      maxFriendlyActions: 2,
      requiredWeaponSequence: ["sparrow", "harpoon"],
    },
    playerPlacements: [
      { id: "battleship", start: c(0, 7), orientation: "east" },
      { id: "cruiser", start: c(4, 5), orientation: "east" },
    ],
    enemyPlacements: [
      { id: "cruiser", start: c(1, 1), orientation: "south" },
      { id: "destroyer", start: c(4, 6), orientation: "east" },
      { id: "submarine", start: c(7, 0), orientation: "east" },
    ],
    enemyInitialHits: [c(1, 1), c(1, 4), c(5, 6)],
    initiallyIdentified: ["cruiser", "destroyer"],
    enemyDisclosure: {
      known: ["cruiser", "destroyer"],
      unknownCount: 1,
      callsigns: { cruiser: "CA-04 MERIDIAN", destroyer: "DD-03 TRANSIT" },
      summary: "MERIDIANはB-2からE-2へ南進、両端損傷。TRANSITはG-5からG-7へ東進、中央区画損傷。",
    },
    fixedSeed: 0x6e1903,
    aiSkill: 2.02,
    huntBreadth: 1,
    completion: {
      success: "CROSS BEARING CLOSED：二船影へ異なる射法を割り当て、指定順序で交戦能力を減殺。",
      deadline: "FIRE PLAN EXPIRED：二つの射撃解を行動窓内に処理できず。",
    },
  },
  {
    id: 20,
    sortOrder: 40,
    difficulty: 6,
    category: "extreme",
    title: "COMMAND SECTIONS",
    subtitle: "損傷船影から三つの重要区画を割り出し、撃沈ではなく識別を完了せよ。",
    directive: "公開された船影と重要区画規定を照合。CV、BB、SSの指揮区画へ通常砲撃を一射ずつ実施し、三目標を識別せよ。",
    condition: "CV・BB・SS識別 / 通常砲撃のみ / 3行動",
    fleet: ["battleship", "destroyer"],
    playerFleet: ["battleship", "destroyer"],
    enemyFleet: ["carrier", "battleship", "cruiser", "destroyer", "submarine"],
    enemyFirst: false,
    allowedWeapons: ["fire"],
    objective: {
      kind: "identify-targets",
      targets: ["carrier", "battleship", "submarine"],
      maxFriendlyActions: 3,
      requiredWeaponSequence: ["fire", "fire", "fire"],
    },
    playerPlacements: [
      { id: "battleship", start: c(0, 7), orientation: "east" },
      { id: "destroyer", start: c(5, 6), orientation: "east" },
    ],
    enemyPlacements: [
      { id: "carrier", start: c(0, 0), orientation: "east" },
      { id: "battleship", start: c(0, 3), orientation: "east" },
      { id: "cruiser", start: c(4, 5), orientation: "east" },
      { id: "destroyer", start: c(0, 6), orientation: "east" },
      { id: "submarine", start: c(7, 7), orientation: "east" },
    ],
    enemyInitialHits: [
      c(0, 0), c(1, 0), c(3, 0), c(0, 1), c(1, 1), c(2, 1), c(3, 1),
      c(0, 3), c(1, 3), c(3, 3), c(4, 3),
    ],
    enemyDisclosure: {
      known: ["carrier", "battleship", "submarine"],
      unknownCount: 2,
      candidateCells: [
        { code: "AIR CONTROL", coord: c(2, 0) },
        { code: "MAIN DIRECTOR", coord: c(2, 3) },
        { code: "CONNING TOWER", coord: c(7, 7) },
      ],
      summary: "二つの大形船影と単独音源を確認。未被弾区画に残る指揮機能を識別射撃で確定せよ。",
    },
    fixedSeed: 0x6e2004,
    aiSkill: 2.06,
    huntBreadth: 1,
    completion: {
      success: "COMMAND SECTIONS FIXED：三重要区画への命中により、全指定目標の艦種を確定。",
      deadline: "IDENTIFICATION WINDOW CLOSED：三目標の識別完了前に射撃窓を消費。",
    },
  },
  {
    id: 21,
    sortOrder: 50,
    difficulty: 6,
    category: "extreme",
    title: "OPERATION MOBY-DICK",
    subtitle: "追跡網を破って静粛移動する戦略潜航艦LEVIATHANを二度の有効接触で拘束せよ。",
    directive: "四方反響の交点D-4へ初弾。緊急潜航後は公開された四つの離脱区画をF-4一波で同時制圧せよ。",
    condition: "SSX-02 LEVIATHAN撃沈 / CV・DE生存 / 2行動",
    fleet: ["leviathan"],
    playerFleet: ["carrier", "escort"],
    enemyFleet: ["leviathan"],
    enemyFirst: true,
    allowedWeapons: ["fire", "phantom"],
    objective: {
      kind: "destroy-targets",
      targets: ["leviathan"],
      protectedShips: ["carrier", "escort"],
      maxFriendlyActions: 2,
      requiredWeaponSequence: ["fire", "phantom"],
    },
    playerPlacements: [
      { id: "carrier", start: c(0, 0), orientation: "east" },
      { id: "escort", start: c(1, 2), orientation: "east" },
    ],
    enemyPlacements: [{ id: "leviathan", start: leviathanOrigin, orientation: "east" }],
    initialIntel: leviathanNet,
    enemyDisclosure: {
      known: ["leviathan"],
      unknownCount: 0,
      callsigns: { leviathan: "SSX-02 LEVIATHAN" },
      candidateCells: [
        { code: "EGRESS ALPHA / B-2", coord: leviathanEgress[0] },
        { code: "EGRESS BRAVO / B-7", coord: leviathanEgress[1] },
        { code: "EGRESS CHARLIE / G-2", coord: leviathanEgress[2] },
        { code: "EGRESS DELTA / G-7", coord: leviathanEgress[3] },
      ],
      summary: "接触呼称LEVIATHAN。D-4に反響方位が収束。初回命中後の静粛離脱先は四区画まで限定済み。",
    },
    requiredLink: "carrier",
    fixedSeed: 0x6e2105,
    aiSkill: 2.12,
    huntBreadth: 1,
    completion: {
      success: "LEVIATHAN CONTAINED：初回接触後の静粛離脱を予測し、航空制圧線内で二度目の有効接触を取得。",
      deadline: "LEVIATHAN LOST：静粛離脱後の四候補区画を同一波で拘束できず、接触を喪失。",
      protected: {
        carrier: "AIR SEARCH ABORTED：航空母艦喪失。離脱海面の同時制圧不能。",
        escort: "ESCORT SCREEN LOST：護衛連接喪失。第二次出撃の確保不能。",
      },
    },
  },
  {
    id: 22,
    sortOrder: 60,
    difficulty: 6,
    category: "extreme",
    title: "NO SECOND SALVO",
    subtitle: "残存各一射を五つの損傷目標へ割り当て、再射なしで全接触を処理せよ。",
    directive: "F-4、HARPOON、STRADDLE、MK-45 IIは各一回のみ。五目標の残存区画を四つの射法へ割り当てよ。",
    condition: "敵5艦撃沈 / 特殊兵装各1回のみ / 4行動",
    fleet: ["carrier", "battleship", "cruiser", "destroyer", "escort"],
    playerFleet: ["carrier", "battleship", "cruiser", "destroyer"],
    enemyFleet: ["carrier", "battleship", "cruiser", "destroyer", "escort"],
    enemyFirst: false,
    allowedWeapons: ["phantom", "harpoon", "sparrow", "mk45"],
    objective: {
      kind: "destroy-targets",
      targets: ["carrier", "battleship", "cruiser", "destroyer", "escort"],
      maxFriendlyActions: 4,
      requiredWeaponUses: { phantom: 1, harpoon: 1, sparrow: 1, mk45: 1 },
    },
    playerPlacements: [
      { id: "carrier", start: c(0, 0), orientation: "east" },
      { id: "battleship", start: c(0, 3), orientation: "east" },
      { id: "cruiser", start: c(4, 5), orientation: "east" },
      { id: "destroyer", start: c(5, 7), orientation: "east" },
    ],
    enemyPlacements: [
      { id: "carrier", start: c(0, 0), orientation: "east" },
      { id: "escort", start: c(6, 1), orientation: "east" },
      { id: "battleship", start: c(0, 3), orientation: "east" },
      { id: "cruiser", start: c(4, 5), orientation: "east" },
      { id: "destroyer", start: c(5, 7), orientation: "east" },
    ],
    enemyInitialHits: [
      c(1, 0), c(2, 0), c(3, 0), c(0, 1), c(1, 1), c(2, 1), c(3, 1),
      c(7, 1),
      c(0, 3), c(1, 3), c(2, 3), c(3, 3),
      c(5, 5), c(6, 5), c(7, 5),
      c(5, 7), c(6, 7),
    ],
    initiallyIdentified: ["carrier", "battleship", "cruiser", "destroyer", "escort"],
    enemyDisclosure: {
      known: ["carrier", "battleship", "cruiser", "destroyer", "escort"],
      unknownCount: 0,
      callsigns: {
        carrier: "CV-08 ASCENDANT",
        battleship: "BB-05 RESOLUTE",
        cruiser: "CA-04 LANCER",
        destroyer: "DD-03 SWIFT",
        escort: "DE-01 WARD",
      },
      summary: "全目標を識別済み。各艦は一残存区画。F-4だけが離隔した二目標を一行動で処理できる。",
    },
    initialArsenal: { phantom: 2, harpoon: 2, sparrow: 1, mk45: 1 },
    fixedSeed: 0x6e2206,
    aiSkill: 2.18,
    huntBreadth: 1,
    completion: {
      success: "FIRE DISTRIBUTION COMPLETE：四射法を重複なく配分し、五つの残存接触を再射なしで減殺。",
      deadline: "MAGAZINE PLAN FAILED：残存弾庫の配分を誤り、未処理接触を残置。",
    },
  },
];
