import type { MissionStageDefinition } from "./Campaign.ts";

/**
 * Fixed, non-random lessons. Enemy turns are suppressed by the training plan;
 * the hostile fleet only provides a deterministic board for the instructed
 * order.
 */
export const TRAINING_STAGES: ReadonlyArray<MissionStageDefinition> = [
  {
    id: 107,
    sortOrder: 5,
    difficulty: 1,
    category: "training",
    title: "FLEET DEPLOYMENT",
    subtitle: "艦を置き、向きと占有区画を確認してから最初の射撃を行う。",
    directive: "駆逐艦を指定位置へ配備し、D-4へFIREを実行せよ。",
    condition: "配置訓練→FIRE / 1行動 / 敵行動なし",
    fleet: ["submarine"],
    playerFleet: ["destroyer"],
    enemyFleet: ["submarine"],
    enemyFirst: false,
    allowedWeapons: ["fire"],
    objective: { kind: "destroy-targets", targets: ["submarine"], maxFriendlyActions: 1 },
    playerPlacements: [{ id: "destroyer", start: { x: 1, y: 4 }, orientation: "south" }],
    enemyPlacements: [{ id: "submarine", start: { x: 3, y: 3 }, orientation: "east" }],
    initiallyIdentified: ["submarine"],
    enemyDisclosure: { known: ["submarine"], unknownCount: 0, summary: "訓練標的SSをD-4に表示。" },
    fixedSeed: 0x540707,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 7,
      plainBrief: "まず自軍海域で艦を配置します。駆逐艦をE-2へ移動し、回転して下向きにするとE-2～G-2の3区画を使います。配置を確定して戦闘を開始したら、敵海域のD-4を選んでFIREを押してください。",
      doctrine: "FLEET DEPLOYMENT / FIRST FIRE",
      suppressEnemyActions: true,
      placementDrill: {
        title: "STEP 1 / 艦隊配置",
        instruction: "駆逐艦をE-2へ移動し、ROTATEで艦首を南（下）へ向けて配置を確定します。",
        placements: [{ id: "destroyer", start: { x: 1, y: 4 }, orientation: "south" }],
        confirmLabel: "配置完了・戦闘開始",
      },
      steps: [{
        title: "STEP 2 / FIRST FIRE",
        instruction: "敵海域へ切り替え、D-4を選んでFIREを実行します。",
        doctrine: "SELECT D-4 / AUTHORIZE FIRE",
        expected: { weapon: "fire", target: { x: 3, y: 3 } },
        highlight: [{ x: 3, y: 3 }],
      }],
      debrief: ["艦の位置と向きを確定して出撃しました。", "敵海域へ切り替え、座標を指定して射撃しました。"],
    },
    completion: {
      success: "TRAINING COMPLETE：配置から初回射撃までの手順を完了した。",
      deadline: "TRAINING RESET：駆逐艦をE-2から南向きに配備し、D-4へFIREを実行せよ。",
    },
  },
  {
    id: 101,
    sortOrder: 10,
    difficulty: 1,
    category: "training",
    title: "TACTICAL PLOT",
    subtitle: "戦術図の座標を読み、単発射撃を実行する。",
    directive: "表示された目標区画へFIREを実行せよ。",
    condition: "FIREのみ / 1行動 / 敵行動なし",
    fleet: ["submarine"],
    playerFleet: ["destroyer"],
    enemyFleet: ["submarine"],
    enemyFirst: false,
    allowedWeapons: ["fire"],
    objective: { kind: "destroy-targets", targets: ["submarine"], maxFriendlyActions: 1 },
    playerPlacements: [{ id: "destroyer", start: { x: 0, y: 7 }, orientation: "east" }],
    enemyPlacements: [{ id: "submarine", start: { x: 3, y: 3 }, orientation: "east" }],
    initiallyIdentified: ["submarine"],
    enemyDisclosure: { known: ["submarine"], unknownCount: 0, summary: "SSをD-4に表示。" },
    fixedSeed: 0x540101,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 1,
      plainBrief: "盤面は上からA～H、左から1～8です。D-4を選んで単発射撃してください。",
      doctrine: "TACTICAL PLOT / FIRE ORDER",
      suppressEnemyActions: true,
      steps: [{
        title: "FIRE CONTROL",
        instruction: "D-4を選び、FIREを実行します。",
        doctrine: "SELECT D-4 / AUTHORIZE FIRE",
        expected: { weapon: "fire", target: { x: 3, y: 3 } },
        highlight: [{ x: 3, y: 3 }],
      }],
      debrief: ["座標D-4を正しく指定しました。", "単発射撃の基本操作を確認しました。"],
    },
    completion: {
      success: "TRAINING COMPLETE：戦術図から射撃座標を正しく指定した。",
      deadline: "TRAINING RESET：指定されたD-4へFIREを実行せよ。",
    },
  },
  {
    id: 102,
    sortOrder: 20,
    difficulty: 1,
    category: "training",
    title: "ACOUSTIC BEARING",
    subtitle: "四方反響を重ね、斜め方向を除外して接触位置を確定する。",
    directive: "C-4とD-3のECHOが共有するD-4へFIREを実行せよ。",
    condition: "4-DIRECTION ECHO / FIREのみ / 1行動 / 敵行動なし",
    fleet: ["submarine"],
    playerFleet: ["destroyer"],
    enemyFleet: ["submarine"],
    enemyFirst: false,
    allowedWeapons: ["fire"],
    objective: { kind: "destroy-targets", targets: ["submarine"], maxFriendlyActions: 1 },
    playerPlacements: [{ id: "destroyer", start: { x: 0, y: 7 }, orientation: "east" }],
    enemyPlacements: [{ id: "submarine", start: { x: 3, y: 3 }, orientation: "east" }],
    initialIntel: [
      { coord: { x: 3, y: 2 }, mark: "echo" },
      { coord: { x: 2, y: 3 }, mark: "echo" },
      { coord: { x: 2, y: 2 }, mark: "miss" },
    ],
    enemyDisclosure: {
      known: [],
      unknownCount: 1,
      candidateCells: [{ code: "ECHO FIX / D-4", coord: { x: 3, y: 3 } }],
      summary: "C-4とD-3に四方反響。斜めのC-3はMISS。反響は着弾点の上下左右だけを示す。",
    },
    fixedSeed: 0x540202,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 2,
      plainBrief: "ECHOは、着弾点の上下左右4方向のどこかに生存区画がある合図です。斜め方向は含みません。C-4とD-3の反響が重なるD-4を狙ってください。",
      doctrine: "ACOUSTIC BEARING / ORTHOGONAL ECHO",
      suppressEnemyActions: true,
      steps: [{
        title: "ECHO FIX",
        instruction: "二つの四方反響が共有するD-4を選び、FIREを実行します。",
        doctrine: "CROSS BEARINGS / FIX D-4 / AUTHORIZE FIRE",
        expected: { weapon: "fire", target: { x: 3, y: 3 } },
        highlight: [{ x: 3, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 3 }],
      }],
      debrief: ["二つの四方反響からD-4を確定しました。", "ECHOは上下左右のみを示し、斜め方向を含みません。"],
    },
    completion: {
      success: "TRAINING COMPLETE：四方反響を重ね、接触位置を確定した。",
      deadline: "TRAINING RESET：C-4とD-3の四方反響からD-4を求めよ。",
    },
  },
  {
    id: 103,
    sortOrder: 30,
    difficulty: 2,
    category: "training",
    title: "CROSS FIX",
    subtitle: "四方反響と既存損傷から船影を復元し、夾叉射撃の射撃扇を合わせる。",
    directive: "E-5を基準に北向きのSTRADDLEを実行せよ。",
    condition: "8-INCH STRADDLEのみ / 1行動 / 敵行動なし",
    fleet: ["cruiser"],
    playerFleet: ["cruiser"],
    enemyFleet: ["cruiser"],
    enemyFirst: false,
    allowedWeapons: ["sparrow"],
    objective: { kind: "destroy-targets", targets: ["cruiser"], maxFriendlyActions: 1 },
    playerPlacements: [{ id: "cruiser", start: { x: 0, y: 7 }, orientation: "east" }],
    enemyPlacements: [{ id: "cruiser", start: { x: 2, y: 3 }, orientation: "east" }],
    enemyInitialHits: [{ x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
    initialIntel: [
      { coord: { x: 5, y: 4 }, mark: "echo" },
      { coord: { x: 6, y: 3 }, mark: "echo" },
      { coord: { x: 6, y: 4 }, mark: "miss" },
    ],
    initiallyIdentified: ["cruiser"],
    enemyDisclosure: { known: ["cruiser"], unknownCount: 0, summary: "CAの残存区画D-6を表示。" },
    fixedSeed: 0x540303,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 3,
      plainBrief: "D-6の下と右側にある反響、斜めのMISS、既存損傷を重ねると横向きの船影を復元できます。E-5を基準に射撃扇を北へ向けてください。",
      doctrine: "CROSS FIX / HULL PICTURE / STRADDLE SOLUTION",
      suppressEnemyActions: true,
      steps: [{
        title: "RANGING ORDER",
        instruction: "E-5を選び、射撃方向を北にして8-INCH STRADDLEを実行します。",
        doctrine: "ANCHOR E-5 / FAN NORTH",
        expected: { weapon: "sparrow", anchor: { x: 4, y: 4 }, orientation: "north" },
        highlight: [{ x: 4, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 5, y: 3 }],
      }],
      debrief: ["四方反響から船影の残存方向を復元しました。", "基準区画と方位でSTRADDLEを指定する手順を確認しました。"],
    },
    completion: {
      success: "TRAINING COMPLETE：交差情報から射撃扇を確定した。",
      deadline: "TRAINING RESET：E-5基準、北向きのSTRADDLEを実行せよ。",
    },
  },
  {
    id: 104,
    sortOrder: 40,
    difficulty: 2,
    category: "training",
    title: "ESCORT SUPPORT",
    subtitle: "護衛リンクによる追加出撃を使い、二つの水上目標へ航空攻撃を継続する。",
    directive: "C列のBB残存4区画、続いてE列のCA全4区画へF-4 PHANTOMを二回発進させよ。",
    condition: "F-4 PHANTOM 2回 / ESCORT SUPPORT ACTIVE / 敵行動なし",
    fleet: ["battleship", "cruiser"],
    playerFleet: ["carrier", "escort"],
    enemyFleet: ["battleship", "cruiser"],
    enemyFirst: false,
    allowedWeapons: ["phantom"],
    objective: { kind: "destroy-targets", targets: ["battleship", "cruiser"], maxFriendlyActions: 2, protectedShips: ["carrier", "escort"] },
    playerPlacements: [
      { id: "carrier", start: { x: 1, y: 5 }, orientation: "east" },
      { id: "escort", start: { x: 1, y: 4 }, orientation: "east" },
    ],
    enemyPlacements: [
      { id: "battleship", start: { x: 1, y: 2 }, orientation: "east" },
      { id: "cruiser", start: { x: 1, y: 4 }, orientation: "east" },
    ],
    enemyInitialHits: [{ x: 1, y: 2 }],
    initiallyIdentified: ["battleship", "cruiser"],
    enemyDisclosure: { known: ["battleship", "cruiser"], unknownCount: 0, summary: "BBの残存4区画C-3～C-6と、CAの4区画E-2～E-5を表示。" },
    requiredLink: "carrier",
    fixedSeed: 0x540404,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 4,
      plainBrief: "空母に護衛艦の全区画が上下左右で隣接するとESCORT SUPPORTが成立し、F-4を通常の1回に加えてもう1回出撃できます。二波を順に割り当ててください。",
      doctrine: "ESCORT SUPPORT / LINK ACTIVE",
      suppressEnemyActions: true,
      steps: [
        {
          title: "FIRST SORTIE",
          instruction: "C-3、C-4、C-5、C-6を選び、第一波を発進させます。選択順は自由です。",
          doctrine: "BB REMNANT / FOUR TARGETS / LAUNCH F-4",
          expected: { weapon: "phantom", targets: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 5, y: 2 }] },
          highlight: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
        },
        {
          title: "ESCORT-SUPPORTED SORTIE",
          instruction: "追加出撃枠でE-2、E-3、E-4、E-5へ第二波を発進させます。",
          doctrine: "LINK ACTIVE / SECOND SORTIE / LAUNCH F-4",
          expected: { weapon: "phantom", targets: [{ x: 1, y: 4 }, { x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }] },
          highlight: [{ x: 1, y: 4 }, { x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }],
        },
      ],
      debrief: ["二波の航空攻撃を継続しました。", "護衛リンク成立中はF-4出撃回数が1回増加します。空母または護衛艦の喪失、隣接解除で追加枠を失います。"],
    },
    completion: {
      success: "TRAINING COMPLETE：ESCORT SUPPORT下で二波の航空攻撃を完了した。",
      deadline: "TRAINING RESET：護衛連接を確認し、指定二目標へF-4を二回実行せよ。",
      protected: {
        carrier: "FLIGHT CONTROL LOST：空母を維持して訓練を再開せよ。",
        escort: "ESCORT SUPPORT LOST：護衛リンクを維持して訓練を再開せよ。",
      },
    },
  },
  {
    id: 105,
    sortOrder: 50,
    difficulty: 3,
    category: "training",
    title: "FIRE CONTROL LINK",
    subtitle: "戦艦の交差弾道と護衛艦による追加発射を、一つの射撃計画で確認する。",
    directive: "C-2、C-4、C-6を中心にHARPOONを三回発射し、BB残存3区画を処理せよ。",
    condition: "HARPOON 3回 / FIRE CONTROL LINK ACTIVE / 敵行動なし",
    fleet: ["battleship"],
    playerFleet: ["battleship", "escort"],
    enemyFleet: ["battleship"],
    enemyFirst: false,
    allowedWeapons: ["harpoon"],
    objective: { kind: "destroy-targets", targets: ["battleship"], maxFriendlyActions: 3, protectedShips: ["battleship", "escort"] },
    playerPlacements: [
      { id: "battleship", start: { x: 0, y: 6 }, orientation: "east" },
      { id: "escort", start: { x: 0, y: 5 }, orientation: "east" },
    ],
    enemyPlacements: [{ id: "battleship", start: { x: 1, y: 2 }, orientation: "east" }],
    enemyInitialHits: [{ x: 2, y: 2 }, { x: 4, y: 2 }],
    initiallyIdentified: ["battleship"],
    enemyDisclosure: { known: ["battleship"], unknownCount: 0, summary: "BBはC-2～C-6を東西に占位。C-3、C-5損傷、残存3区画。" },
    requiredLink: "battleship",
    fixedSeed: 0x540505,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 5,
      plainBrief: "HARPOONは中心と斜め4方向のX字5区画を攻撃します。この横向きのBBには中心弾だけが届くため3射必要です。戦艦と護衛艦の全区画が隣接しているので、通常2回に追加の1回が認可されています。",
      doctrine: "FIRE CONTROL LINK / HARPOON SOLUTION",
      suppressEnemyActions: true,
      steps: [
        {
          title: "MISSILE ORDER 1",
          instruction: "C-2を中心にHARPOONを発射します。",
          doctrine: "CENTER C-2 / RELEASE ONE",
          expected: { weapon: "harpoon", center: { x: 1, y: 2 } },
          highlight: [{ x: 1, y: 2 }],
        },
        {
          title: "MISSILE ORDER 2",
          instruction: "C-4を中心にHARPOONを発射します。",
          doctrine: "CENTER C-4 / RELEASE TWO",
          expected: { weapon: "harpoon", center: { x: 3, y: 2 } },
          highlight: [{ x: 3, y: 2 }],
        },
        {
          title: "LINK-AUTHORIZED SALVO",
          instruction: "護衛連接による追加発射枠を使い、C-6を中心に第三射を発射します。",
          doctrine: "FIRE CONTROL LINK / CENTER C-6 / RELEASE THREE",
          expected: { weapon: "harpoon", center: { x: 5, y: 2 } },
          highlight: [{ x: 5, y: 2 }],
        },
      ],
      debrief: ["戦艦のX字射界と中心弾を確認しました。", "護衛リンク成立中はHARPOON発射回数が1回増加します。戦艦または護衛艦の喪失、隣接解除で追加枠を失います。"],
    },
    completion: {
      success: "TRAINING COMPLETE：FIRE CONTROL LINK下で三射の交差射撃を完了した。",
      deadline: "TRAINING RESET：残存3区画へHARPOONを三回配分せよ。",
      protected: {
        battleship: "LAUNCH PLATFORM LOST：戦艦を維持して訓練を再開せよ。",
        escort: "FIRE CONTROL LINK LOST：護衛リンクを維持して訓練を再開せよ。",
      },
    },
  },
  {
    id: 106,
    sortOrder: 60,
    difficulty: 3,
    category: "training",
    title: "SILENT TRACE",
    subtitle: "潜水艦の行動後音紋と2×2受動聴音を照合し、単独接触を確定する。",
    directive: "E-5でCONTACT、G-7でNO CONTACTを報告後、F-6へFIREを実行せよ。",
    condition: "PASSIVE SONAR 2回→FIRE / 潜水艦特性 / 敵行動なし",
    fleet: ["submarine"],
    playerFleet: ["submarine"],
    enemyFleet: ["submarine"],
    enemyFirst: false,
    allowedWeapons: ["radar", "fire"],
    objective: {
      kind: "scan-and-destroy",
      targets: ["submarine"],
      maxFriendlyActions: 3,
      protectedShips: ["submarine"],
      reports: [
        { origin: { x: 4, y: 4 }, contact: true, code: "ALPHA / E-5" },
        { origin: { x: 6, y: 6 }, contact: false, code: "BRAVO / G-7" },
      ],
    },
    playerPlacements: [{ id: "submarine", start: { x: 0, y: 7 }, orientation: "east" }],
    enemyPlacements: [{ id: "submarine", start: { x: 5, y: 5 }, orientation: "east" }],
    initialEnemyWakes: [{ x: 4, y: 4 }, { x: 6, y: 4 }],
    enemyDisclosure: {
      known: [],
      unknownCount: 1,
      candidateCells: [
        { code: "ALPHA / E-5", coord: { x: 4, y: 4 } },
        { code: "BRAVO / G-7", coord: { x: 6, y: 6 } },
      ],
      summary: "単独潜航接触。直前二行動の音紋を表示。敵味方とも、潜水艦だけになった後は潜水艦が行動するたび周辺の未表示区画へ音紋を一つ残す。",
    },
    fixedSeed: 0x540606,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 6,
      plainBrief: "潜水艦だけが残ると、その潜水艦が行動した後に周囲8区画の未表示地点へ音紋が一つ出ます。音紋は艦そのものではなく周辺の手掛かりです。2×2のPASSIVE SONARで候補海面を絞り、最後に射撃します。敵味方とも条件は同じです。",
      doctrine: "SILENT TRACE / PASSIVE CLASSIFICATION",
      suppressEnemyActions: true,
      steps: [
        {
          title: "LISTENING REPORT ALPHA",
          instruction: "E-5を左上にしてPASSIVE SONARを実行し、CONTACTを確認します。",
          doctrine: "ALPHA E-5 / LISTEN AND REPORT",
          expected: { weapon: "radar", origin: { x: 4, y: 4 } },
          highlight: [{ x: 4, y: 4 }, { x: 5, y: 4 }, { x: 4, y: 5 }, { x: 5, y: 5 }],
        },
        {
          title: "LISTENING REPORT BRAVO",
          instruction: "G-7を左上にしてPASSIVE SONARを実行し、NO CONTACTを確認します。",
          doctrine: "BRAVO G-7 / NEGATIVE CONTACT",
          expected: { weapon: "radar", origin: { x: 6, y: 6 } },
          highlight: [{ x: 6, y: 6 }, { x: 7, y: 6 }, { x: 6, y: 7 }, { x: 7, y: 7 }],
        },
        {
          title: "CONTACT CLOSE",
          instruction: "二つの報告と音紋を照合し、F-6へFIREを実行します。",
          doctrine: "FIX F-6 / AUTHORIZE FIRE",
          expected: { weapon: "fire", target: { x: 5, y: 5 } },
          highlight: [{ x: 5, y: 5 }],
        },
      ],
      debrief: ["音紋を艦位置そのものと誤認せず、受動聴音で候補を絞りました。", "潜水艦のみになった後の行動後音紋と、PASSIVE SONARの2×2判定を確認しました。"],
    },
    completion: {
      success: "TRAINING COMPLETE：音紋・CONTACT・NO CONTACTを照合し、潜航接触を確定した。",
      deadline: "TRAINING RESET：ALPHA、BRAVOを聴音後、F-6へ射撃せよ。",
      protected: { submarine: "LISTENING POST LOST：自軍潜水艦を維持して訓練を再開せよ。" },
    },
  },
  {
    id: 108,
    sortOrder: 70,
    difficulty: 1,
    category: "training",
    title: "DAMAGE REPORT",
    subtitle: "敵弾着を見届け、損傷報告を確認してから反撃へ移る。",
    directive: "損傷報告を確認後、敵海域D-4へFIREを実行せよ。",
    condition: "敵単発射撃デモ→損傷報告→FIRE / 敵通常行動なし",
    fleet: ["submarine"],
    playerFleet: ["destroyer"],
    enemyFleet: ["submarine"],
    enemyFirst: true,
    allowedWeapons: ["fire"],
    objective: { kind: "destroy-targets", targets: ["submarine"], maxFriendlyActions: 1, protectedShips: ["destroyer"] },
    playerInitialHits: [{ x: 1, y: 5 }],
    playerPlacements: [{ id: "destroyer", start: { x: 1, y: 5 }, orientation: "east" }],
    enemyPlacements: [{ id: "submarine", start: { x: 3, y: 3 }, orientation: "east" }],
    initiallyIdentified: ["submarine"],
    enemyDisclosure: { known: ["submarine"], unknownCount: 0, summary: "反撃訓練標的SSをD-4に表示。" },
    fixedSeed: 0x540808,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 8,
      plainBrief: "敵の攻撃中は自軍海域を見て着弾を確認します。攻撃が終わると損傷報告が止まって表示されるので、内容を読んでから反撃へ進みます。この訓練ではF-2に1区画の損傷を受けますが、駆逐艦はまだ行動できます。",
      doctrine: "DAMAGE CONTROL / REPORT ACKNOWLEDGMENT",
      suppressEnemyActions: true,
      enemyDemonstration: {
        title: "ENEMY ACTION / 敵砲撃",
        instruction: "自軍海域のF-2への着弾を確認し、表示された損傷報告を読みます。",
        weaponLabel: "FIRE",
        target: { x: 1, y: 5 },
        result: "hit",
        ship: "destroyer",
        damageReport: ["駆逐艦 F-2：1区画損傷。", "残存2/3区画。戦闘継続可能。"],
        acknowledgmentLabel: "損傷報告を確認・反撃へ",
      },
      steps: [{
        title: "COUNTER FIRE",
        instruction: "損傷報告を確認したら敵海域へ切り替え、D-4へFIREを実行します。",
        doctrine: "REPORT ACKNOWLEDGED / FIX D-4 / RETURN FIRE",
        expected: { weapon: "fire", target: { x: 3, y: 3 } },
        highlight: [{ x: 3, y: 3 }],
      }],
      debrief: ["敵弾着から損傷報告までを自軍海域で確認しました。", "報告を確認してから、敵海域へ切り替えて反撃しました。"],
    },
    completion: {
      success: "TRAINING COMPLETE：損傷報告を確認し、戦闘継続可能と判断して反撃した。",
      deadline: "TRAINING RESET：損傷報告を確認後、D-4へFIREを実行せよ。",
      protected: { destroyer: "ACTION PLATFORM LOST：駆逐艦の残存区画を確認し、訓練を再開せよ。" },
    },
  },
  {
    id: 109,
    sortOrder: 80,
    difficulty: 2,
    category: "training",
    title: "IMPORTANT SECTION",
    subtitle: "重要区画への命中で敵艦を識別し、二点同時射撃を完了する。",
    directive: "C-5の重要区画を含むC-4、C-5へMK-45 IIを実行せよ。",
    condition: "IMPORTANT SECTION / MK-45 II 2点選択 / 1行動 / 敵行動なし",
    fleet: ["cruiser"],
    playerFleet: ["destroyer"],
    enemyFleet: ["cruiser"],
    enemyFirst: false,
    allowedWeapons: ["mk45"],
    objective: {
      kind: "destroy-targets",
      targets: ["cruiser"],
      maxFriendlyActions: 1,
      protectedShips: ["destroyer"],
    },
    playerPlacements: [{ id: "destroyer", start: { x: 1, y: 6 }, orientation: "east" }],
    enemyPlacements: [{ id: "cruiser", start: { x: 2, y: 2 }, orientation: "east" }],
    enemyInitialHits: [{ x: 2, y: 2 }, { x: 5, y: 2 }],
    enemyDisclosure: {
      known: [],
      unknownCount: 1,
      candidateCells: [{ code: "CONTROL SECTION / C-5", coord: { x: 4, y: 2 } }],
      summary: "未識別接触。C-3、C-6損傷。情報資料はC-5を重要区画候補としている。",
    },
    fixedSeed: 0x540909,
    aiSkill: 0,
    huntBreadth: 1,
    training: {
      lesson: 9,
      plainBrief: "敵艦には1区画だけ重要区画があります。そこへ命中すると艦種を識別できますが、追加ダメージや残りの艦影は分かりません。MK-45 IIは離れた2区画を一度に選べます。C-5の重要区画と、もう一つの残存区画C-4を選んでください。",
      doctrine: "IMPORTANT SECTION / TWO-POINT FIRE CONTROL",
      suppressEnemyActions: true,
      steps: [{
        title: "CLASSIFY AND FINISH",
        instruction: "重要区画C-5と残存区画C-4の二点を選び、MK-45 IIを実行します。選択順は自由です。",
        doctrine: "SELECT C-5 + C-4 / AUTHORIZE MK-45 II",
        expected: { weapon: "mk45", targets: [{ x: 4, y: 2 }, { x: 3, y: 2 }] },
        highlight: [{ x: 4, y: 2 }, { x: 3, y: 2 }],
      }],
      debrief: ["重要区画への命中で、未識別接触を巡洋艦として識別しました。", "MK-45 IIで離れた二点を一度に指定しました。重要区画命中による追加ダメージはありません。"],
    },
    completion: {
      success: "TRAINING COMPLETE：重要区画を捉え、二点同時射撃で接触を処理した。",
      deadline: "TRAINING RESET：C-5とC-4へMK-45 IIを実行せよ。",
      protected: { destroyer: "FIRE CONTROL LOST：駆逐艦を維持して訓練を再開せよ。" },
    },
  },
];
